/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Article = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : ExternalBlob,
  'timestamp' : Time,
});
export const HomePageLink = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : ExternalBlob,
});
export const Resource = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Spotlight = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
});
export const Wisdom = IDL.Record({
  'id' : IDL.Text,
  'quote' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
});
export const XPost = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'image' : ExternalBlob,
});
export const MissionContent = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addArticle' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
  'addCybercrimeArticle' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
  'addHomePageLink' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
  'addResource' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addSpotlight' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'addWisdom' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addXPost' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'deleteArticle' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteCybercrimeArticle' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteHomePageLink' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteResource' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteSpotlight' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteWisdom' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteXPost' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllCybercrimeArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllHomePageLinks' : IDL.Func([], [IDL.Vec(HomePageLink)], ['query']),
  'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getAllSpotlights' : IDL.Func([], [IDL.Vec(Spotlight)], ['query']),
  'getAllWisdom' : IDL.Func([], [IDL.Vec(Wisdom)], ['query']),
  'getAllXPosts' : IDL.Func([], [IDL.Vec(XPost)], ['query']),
  'getArticlesSortedByTitle' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getMissionContent' : IDL.Func([], [IDL.Opt(MissionContent)], ['query']),
  'updateArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Bool],
      [],
    ),
  'updateCybercrimeArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Bool],
      [],
    ),
  'updateHomePageLink' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Bool],
      [],
    ),
  'updateMissionContent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(ExternalBlob)],
      [],
      [],
    ),
  'updateResource' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateSpotlight' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateWisdom' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateXPost' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Article = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : ExternalBlob,
    'timestamp' : Time,
  });
  const HomePageLink = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : ExternalBlob,
  });
  const Resource = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Spotlight = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Wisdom = IDL.Record({
    'id' : IDL.Text,
    'quote' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
  });
  const XPost = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'image' : ExternalBlob,
  });
  const MissionContent = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addArticle' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
    'addCybercrimeArticle' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'addHomePageLink' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
    'addResource' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addSpotlight' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'addWisdom' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addXPost' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'deleteArticle' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteCybercrimeArticle' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteHomePageLink' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteResource' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteSpotlight' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteWisdom' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteXPost' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllCybercrimeArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllHomePageLinks' : IDL.Func([], [IDL.Vec(HomePageLink)], ['query']),
    'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getAllSpotlights' : IDL.Func([], [IDL.Vec(Spotlight)], ['query']),
    'getAllWisdom' : IDL.Func([], [IDL.Vec(Wisdom)], ['query']),
    'getAllXPosts' : IDL.Func([], [IDL.Vec(XPost)], ['query']),
    'getArticlesSortedByTitle' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getMissionContent' : IDL.Func([], [IDL.Opt(MissionContent)], ['query']),
    'updateArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Bool],
        [],
      ),
    'updateCybercrimeArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Bool],
        [],
      ),
    'updateHomePageLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Bool],
        [],
      ),
    'updateMissionContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(ExternalBlob)],
        [],
        [],
      ),
    'updateResource' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateSpotlight' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Bool],
        [],
      ),
    'updateWisdom' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateXPost' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };