/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : string,
  'url' : string,
  'title' : string,
  'thumbnail' : ExternalBlob,
  'timestamp' : Time,
}
export type ExternalBlob = Uint8Array;
export interface HomePageLink {
  'id' : string,
  'url' : string,
  'title' : string,
  'thumbnail' : ExternalBlob,
}
export interface MissionContent {
  'title' : string,
  'description' : string,
  'images' : Array<ExternalBlob>,
}
export interface Resource {
  'id' : string,
  'url' : string,
  'name' : string,
  'description' : string,
}
export interface Spotlight {
  'id' : string,
  'title' : string,
  'content' : string,
  'link' : [] | [string],
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
}
export type Time = bigint;
export interface Wisdom {
  'id' : string,
  'quote' : string,
  'author' : string,
  'timestamp' : Time,
}
export interface XPost {
  'id' : string,
  'description' : string,
  'timestamp' : Time,
  'image' : ExternalBlob,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addArticle' : ActorMethod<[string, string, ExternalBlob], undefined>,
  'addCybercrimeArticle' : ActorMethod<
    [string, string, ExternalBlob],
    undefined
  >,
  'addHomePageLink' : ActorMethod<[string, string, ExternalBlob], undefined>,
  'addResource' : ActorMethod<[string, string, string], undefined>,
  'addSpotlight' : ActorMethod<
    [string, string, [] | [ExternalBlob], [] | [string]],
    undefined
  >,
  'addWisdom' : ActorMethod<[string, string], undefined>,
  'addXPost' : ActorMethod<[string, ExternalBlob], undefined>,
  'deleteArticle' : ActorMethod<[string], boolean>,
  'deleteCybercrimeArticle' : ActorMethod<[string], boolean>,
  'deleteHomePageLink' : ActorMethod<[string], boolean>,
  'deleteResource' : ActorMethod<[string], boolean>,
  'deleteSpotlight' : ActorMethod<[string], boolean>,
  'deleteWisdom' : ActorMethod<[string], boolean>,
  'deleteXPost' : ActorMethod<[string], boolean>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getAllCybercrimeArticles' : ActorMethod<[], Array<Article>>,
  'getAllHomePageLinks' : ActorMethod<[], Array<HomePageLink>>,
  'getAllResources' : ActorMethod<[], Array<Resource>>,
  'getAllSpotlights' : ActorMethod<[], Array<Spotlight>>,
  'getAllWisdom' : ActorMethod<[], Array<Wisdom>>,
  'getAllXPosts' : ActorMethod<[], Array<XPost>>,
  'getArticlesSortedByTitle' : ActorMethod<[], Array<Article>>,
  'getMissionContent' : ActorMethod<[], [] | [MissionContent]>,
  'updateArticle' : ActorMethod<
    [string, string, string, ExternalBlob],
    boolean
  >,
  'updateCybercrimeArticle' : ActorMethod<
    [string, string, string, ExternalBlob],
    boolean
  >,
  'updateHomePageLink' : ActorMethod<
    [string, string, string, ExternalBlob],
    boolean
  >,
  'updateMissionContent' : ActorMethod<
    [string, string, Array<ExternalBlob>],
    undefined
  >,
  'updateResource' : ActorMethod<[string, string, string, string], boolean>,
  'updateSpotlight' : ActorMethod<
    [string, string, string, [] | [ExternalBlob], [] | [string]],
    boolean
  >,
  'updateWisdom' : ActorMethod<[string, string, string], boolean>,
  'updateXPost' : ActorMethod<[string, string, ExternalBlob], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];